version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"
    labels:
      - "dependencies ğŸ”"
    assignees:
      - "ttattl"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"
    labels:
      - "dependencies ğŸ”"
    assignees:
      - "ttattl"
